"""Canonical Mage checkpoint supply-chain identity manifests.

The manifest intentionally captures only execution inputs: Hugging Face model,
configuration, tokenizer and chat-template assets; trusted remote-code sources;
StreamMind gate code/weights; and neural-codec source/native code/config/checkpoints.
Caches, examples, assets, documentation, generated bytecode, and other incidental
files are excluded by a fixed policy.  The module performs no model load or network I/O.
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path, PurePosixPath
from typing import Annotated, Final, Literal

from pydantic import Field, StringConstraints, ValidationError, model_validator

from robata.contracts.common import Sha256Digest, StrictModel
from robata.contracts.hashing import canonical_json_bytes, exact_bytes_sha256

MAGE_CHECKPOINT_MANIFEST_VERSION: Literal["mage-checkpoint-manifest-v2"] = (
    "mage-checkpoint-manifest-v2"
)
MAGE_CHECKPOINT_INCLUSION_POLICY_VERSION: Final = "mage-execution-inputs-v1"

NonEmptyString = Annotated[str, StringConstraints(strict=True, min_length=1, max_length=4096)]
RelativePosixPath = Annotated[
    str,
    StringConstraints(strict=True, min_length=1, max_length=16_384),
]
NonNegativeInt = Annotated[int, Field(strict=True, ge=0)]
PositiveInt = Annotated[int, Field(strict=True, ge=1)]

_EXCLUDED_DIRECTORY_NAMES: Final = frozenset(
    {
        ".cache",
        ".git",
        "__pycache__",
        "assets",
        "benchmarks",
        "cache",
        "docs",
        "examples",
        "logs",
        "output",
        "outputs",
        "test",
        "tests",
        "tmp",
    }
)
_EXCLUDED_SUFFIXES: Final = frozenset(
    {
        ".bak",
        ".gif",
        ".jpeg",
        ".jpg",
        ".log",
        ".md",
        ".mp4",
        ".orig",
        ".png",
        ".pyo",
        ".pyc",
        ".swp",
        ".tmp",
        ".webp",
    }
)
_CONFIG_OR_TOKENIZER_FILENAMES: Final = frozenset(
    {
        "added_tokens.json",
        "config.json",
        "feature_extractor_config.json",
        "generation_config.json",
        "image_processor_config.json",
        "merges.txt",
        "preprocessor_config.json",
        "processor_config.json",
        "special_tokens_map.json",
        "spiece.model",
        "tokenizer.json",
        "tokenizer.model",
        "tokenizer_config.json",
        "video_preprocessor_config.json",
        "vocab.json",
        "vocab.txt",
    }
)
_WEIGHT_SUFFIXES: Final = (
    ".bin",
    ".ckpt",
    ".gguf",
    ".onnx",
    ".pt",
    ".pth",
    ".safetensors",
)
_REMOTE_CODE_SUFFIXES: Final = frozenset(
    {
        ".c",
        ".cc",
        ".cpp",
        ".cu",
        ".cxx",
        ".dll",
        ".dylib",
        ".h",
        ".hpp",
        ".py",
        ".pyi",
        ".pyd",
        ".so",
    }
)
_NEURAL_CODEC_CONFIGURATION_SUFFIXES: Final = frozenset({".json", ".toml", ".yaml", ".yml"})


class MageCheckpointIdentityError(ValueError):
    """A Mage checkpoint cannot satisfy the pinned supply-chain identity."""


class MageCheckpointFile(StrictModel):
    """One included execution input, addressed only by a safe relative POSIX path."""

    path: RelativePosixPath
    byte_count: NonNegativeInt
    sha256: Sha256Digest

    @model_validator(mode="after")
    def validate_relative_path(self) -> MageCheckpointFile:
        _validate_relative_posix_path(self.path)
        return self


class MageCheckpointManifest(StrictModel):
    """Versioned, self-validating identity for one local Mage checkpoint tree."""

    manifest_version: Literal["mage-checkpoint-manifest-v2"] = MAGE_CHECKPOINT_MANIFEST_VERSION
    inclusion_policy_version: Literal["mage-execution-inputs-v1"] = (
        MAGE_CHECKPOINT_INCLUSION_POLICY_VERSION
    )
    model_identifier: NonEmptyString
    model_revision: NonEmptyString
    included_file_count: PositiveInt
    total_byte_count: NonNegativeInt
    files: Annotated[tuple[MageCheckpointFile, ...], Field(min_length=1)]
    manifest_sha256: Sha256Digest

    @model_validator(mode="after")
    def validate_manifest(self) -> MageCheckpointManifest:
        paths = tuple(entry.path for entry in self.files)
        if paths != tuple(sorted(paths)):
            raise ValueError("manifest files must be sorted by relative POSIX path")
        if len(set(paths)) != len(paths):
            raise ValueError("manifest files must not contain duplicate paths")
        if self.included_file_count != len(self.files):
            raise ValueError("included_file_count does not match files")
        if self.total_byte_count != sum(entry.byte_count for entry in self.files):
            raise ValueError("total_byte_count does not match files")
        if self.manifest_sha256 != _manifest_sha256(
            manifest_version=self.manifest_version,
            inclusion_policy_version=self.inclusion_policy_version,
            model_identifier=self.model_identifier,
            model_revision=self.model_revision,
            included_file_count=self.included_file_count,
            total_byte_count=self.total_byte_count,
            files=self.files,
        ):
            raise ValueError("manifest_sha256 does not match the canonical manifest projection")
        return self


def build_mage_checkpoint_manifest(
    *,
    model_directory: Path,
    model_identifier: str,
    model_revision: str,
) -> MageCheckpointManifest:
    """Build a canonical identity from Mage execution inputs without loading the model."""

    if not isinstance(model_identifier, str) or not model_identifier.strip():
        raise ValueError("model_identifier must be a nonempty string")
    if not isinstance(model_revision, str) or not model_revision.strip():
        raise ValueError("model_revision must be a nonempty string")
    root = _resolve_model_root(model_directory)
    files = tuple(_collect_included_files(root))
    if not files:
        raise MageCheckpointIdentityError("Mage checkpoint contains no included execution inputs")
    total_byte_count = sum(entry.byte_count for entry in files)
    return MageCheckpointManifest(
        model_identifier=model_identifier,
        model_revision=model_revision,
        included_file_count=len(files),
        total_byte_count=total_byte_count,
        files=files,
        manifest_sha256=_manifest_sha256(
            manifest_version=MAGE_CHECKPOINT_MANIFEST_VERSION,
            inclusion_policy_version=MAGE_CHECKPOINT_INCLUSION_POLICY_VERSION,
            model_identifier=model_identifier,
            model_revision=model_revision,
            included_file_count=len(files),
            total_byte_count=total_byte_count,
            files=files,
        ),
    )


def load_mage_checkpoint_manifest(*, manifest_path: Path) -> MageCheckpointManifest:
    """Load and require canonical JSON plus a valid embedded manifest digest."""

    resolved_path = Path(manifest_path).expanduser().resolve()
    try:
        data = resolved_path.read_bytes()
    except OSError as error:
        raise MageCheckpointIdentityError(
            f"Mage checkpoint manifest could not be read: {resolved_path}"
        ) from error
    try:
        manifest = MageCheckpointManifest.model_validate_json(data, strict=True)
    except (TypeError, ValidationError, ValueError) as error:
        raise MageCheckpointIdentityError(
            "Mage checkpoint manifest does not satisfy the pinned contract"
        ) from error
    if canonical_json_bytes(manifest.model_dump(mode="json")) != data:
        raise MageCheckpointIdentityError("Mage checkpoint manifest must use canonical JSON bytes")
    return manifest


def write_mage_checkpoint_manifest(
    *,
    manifest: MageCheckpointManifest,
    manifest_path: Path,
) -> None:
    """Write a self-validating Mage manifest with RFC 8785 canonical JSON bytes."""

    if not isinstance(manifest, MageCheckpointManifest):
        raise TypeError("manifest must be MageCheckpointManifest")
    resolved_path = Path(manifest_path).expanduser().resolve()
    try:
        resolved_path.parent.mkdir(parents=True, exist_ok=True)
        resolved_path.write_bytes(canonical_json_bytes(manifest.model_dump(mode="json")))
    except OSError as error:
        raise MageCheckpointIdentityError(
            f"Mage checkpoint manifest could not be written: {resolved_path}"
        ) from error


def verify_mage_checkpoint_manifest(
    *,
    manifest: MageCheckpointManifest,
    model_directory: Path,
) -> None:
    """Fail when any selected execution input is changed, missing, or newly present."""

    if not isinstance(manifest, MageCheckpointManifest):
        raise TypeError("manifest must be MageCheckpointManifest")
    root = _resolve_model_root(model_directory)
    actual_files = {entry.path: entry for entry in _collect_included_files(root)}
    expected_files = {entry.path: entry for entry in manifest.files}
    missing = sorted(set(expected_files).difference(actual_files))
    unexpected = sorted(set(actual_files).difference(expected_files))
    changed = sorted(
        path
        for path in set(expected_files).intersection(actual_files)
        if expected_files[path] != actual_files[path]
    )
    if missing or unexpected or changed:
        findings: list[str] = []
        if changed:
            findings.append(f"changed included files: {', '.join(changed)}")
        if missing:
            findings.append(f"missing included files: {', '.join(missing)}")
        if unexpected:
            findings.append(f"unexpected included files: {', '.join(unexpected)}")
        raise MageCheckpointIdentityError(
            "Mage checkpoint verification failed: " + "; ".join(findings)
        )


def _collect_included_files(root: Path) -> list[MageCheckpointFile]:
    files: list[MageCheckpointFile] = []
    try:
        for current_root_text, directory_names, filenames in os.walk(
            root,
            topdown=True,
            followlinks=False,
            onerror=_raise_walk_error,
        ):
            current_root = Path(current_root_text)
            retained_directories: list[str] = []
            for directory_name in sorted(directory_names):
                directory_path = current_root / directory_name
                _reject_symlink(directory_path, root)
                _require_within_root(directory_path, root)
                if directory_name.casefold() not in _EXCLUDED_DIRECTORY_NAMES:
                    retained_directories.append(directory_name)
            directory_names[:] = retained_directories
            for filename in sorted(filenames):
                path = current_root / filename
                _reject_symlink(path, root)
                _require_within_root(path, root)
                if not path.is_file():
                    continue
                relative_path = path.relative_to(root)
                if not _includes_execution_input(relative_path):
                    continue
                byte_count, sha256 = _file_metadata(path)
                files.append(
                    MageCheckpointFile(
                        path=relative_path.as_posix(),
                        byte_count=byte_count,
                        sha256=sha256,
                    )
                )
    except OSError as error:
        raise MageCheckpointIdentityError("Mage checkpoint could not be enumerated") from error
    return sorted(files, key=lambda entry: entry.path)


def _includes_execution_input(relative_path: Path) -> bool:
    name = relative_path.name.casefold()
    suffix = relative_path.suffix.casefold()
    if suffix in _EXCLUDED_SUFFIXES:
        return False
    if name in _CONFIG_OR_TOKENIZER_FILENAMES:
        return True
    if name.startswith("chat_template."):
        return True
    if name.startswith("tokenizer.") or name.startswith("vocab.") or name.startswith("merges."):
        return True
    if name == "config.json" or name.endswith("_config.json"):
        return True
    if suffix in _REMOTE_CODE_SUFFIXES:
        return True
    if name.endswith(_WEIGHT_SUFFIXES):
        return True
    if _is_weight_index(name):
        return True
    parts = tuple(part.casefold() for part in relative_path.parts)
    return "neural_codec" in parts and (
        suffix in _NEURAL_CODEC_CONFIGURATION_SUFFIXES or suffix == ".tar"
    )


def _is_weight_index(name: str) -> bool:
    return any(name.endswith(f"{suffix}.index.json") for suffix in _WEIGHT_SUFFIXES)


def _file_metadata(path: Path) -> tuple[int, Sha256Digest]:
    try:
        before = path.stat()
        digest = hashlib.sha256()
        with path.open("rb") as stream:
            for chunk in iter(lambda: stream.read(1024 * 1024), b""):
                digest.update(chunk)
        after = path.stat()
    except OSError as error:
        raise MageCheckpointIdentityError(f"Mage checkpoint could not read {path.name}") from error
    if before.st_size != after.st_size or before.st_mtime_ns != after.st_mtime_ns:
        raise MageCheckpointIdentityError(
            f"Mage checkpoint file changed while hashing: {path.name}"
        )
    return after.st_size, digest.hexdigest()


def _manifest_sha256(
    *,
    manifest_version: str,
    inclusion_policy_version: str,
    model_identifier: str,
    model_revision: str,
    included_file_count: int,
    total_byte_count: int,
    files: tuple[MageCheckpointFile, ...],
) -> Sha256Digest:
    return exact_bytes_sha256(
        canonical_json_bytes(
            {
                "manifest_version": manifest_version,
                "inclusion_policy_version": inclusion_policy_version,
                "model_identifier": model_identifier,
                "model_revision": model_revision,
                "included_file_count": included_file_count,
                "total_byte_count": total_byte_count,
                "files": [entry.model_dump(mode="json") for entry in files],
            }
        )
    )


def _resolve_model_root(model_directory: Path) -> Path:
    try:
        root = Path(model_directory).expanduser().resolve(strict=True)
    except OSError as error:
        raise MageCheckpointIdentityError("Mage model_directory could not be resolved") from error
    if not root.is_dir():
        raise MageCheckpointIdentityError(f"Mage model_directory is not a directory: {root}")
    return root


def _raise_walk_error(error: OSError) -> None:
    raise MageCheckpointIdentityError(
        "Mage checkpoint could not enumerate the model directory"
    ) from error


def _reject_symlink(path: Path, root: Path) -> None:
    if not path.is_symlink():
        return
    try:
        target = path.resolve(strict=True)
    except OSError as error:
        raise MageCheckpointIdentityError(
            f"Mage checkpoint contains an unreadable symlink: {path}"
        ) from error
    if not target.is_relative_to(root):
        raise MageCheckpointIdentityError(f"Mage checkpoint symlink escapes model root: {path}")
    raise MageCheckpointIdentityError(f"Mage checkpoint symlinks are not permitted: {path}")


def _require_within_root(path: Path, root: Path) -> None:
    try:
        resolved = path.resolve(strict=False)
    except OSError as error:
        raise MageCheckpointIdentityError(
            f"Mage checkpoint path could not be resolved: {path}"
        ) from error
    if not resolved.is_relative_to(root):
        raise MageCheckpointIdentityError(f"Mage checkpoint path escapes model root: {path}")


def _validate_relative_posix_path(path: str) -> None:
    posix_path = PurePosixPath(path)
    if (
        "\\" in path
        or path.startswith("/")
        or path.startswith("./")
        or path.endswith("/")
        or "//" in path
        or posix_path.is_absolute()
        or posix_path.as_posix() != path
        or any(part in {"", ".", ".."} for part in posix_path.parts)
    ):
        raise ValueError("manifest file path must be a normalized relative POSIX path")
