"""Event pipeline: proposal, evidence, boundary refinement, fusion, and adjudication."""

from robata.event_pipeline.adjudication import (
    AdjudicationPolicy,
    AdjudicationResult,
    FusionAdjudicator,
)
from robata.event_pipeline.boundary import (
    BoundaryRefinementPolicy,
    BoundaryRefiner,
    RefinedEvent,
)
from robata.event_pipeline.candidate import (
    CandidateEventManager,
    ValidationIssue,
    ValidationResult,
)
from robata.event_pipeline.evidence import ActionEvidenceExtractor
from robata.event_pipeline.fusion import (
    FUSION_STAGES,
    FusionDecision,
    FusionEngine,
    FusionPolicy,
)
from robata.event_pipeline.identity_registry import (
    CrossRecordingEventIdentityError,
    EventIdAllocator,
    EventIdentityAllocationError,
    EventIdentityAssignment,
    EventIdentityAssignmentDisposition,
    EventIdentityAssignmentRelation,
    EventIdentityBatchResult,
    EventIdentityCandidate,
    EventIdentityCandidateRelation,
    EventIdentityConflictError,
    EventIdentityInputError,
    EventIdentityOutboxRecord,
    EventIdentityPolicyRef,
    EventIdentityRegistryError,
    EventIdentityRegistryMutation,
    EventIdentityRegistryRepository,
    EventIdentityRegistryService,
    EventIdentityRelation,
    EventIdentityResolution,
    EventIdentityResolver,
    EventRegistrySnapshot,
    ExactFingerprintEventIdentityResolver,
    InMemoryEventIdentityRegistryRepository,
    PlatformEnrichedEventHypothesis,
    PlatformEnrichedOutputReference,
    ProductionAdmissionProof,
    ProductionAdmittedHypothesisFact,
    ProductionOutputAdmissionPolicyRef,
    ProductionOutputAdmissionProof,
    RandomEventIdAllocator,
    StableEventIdentity,
    StaleEventRegistryFenceError,
)
from robata.event_pipeline.proposer import (
    EventProposer,
    EventProposerConfig,
    MCAPRecording,
    TemporalSignal,
)

__all__ = [
    "FUSION_STAGES",
    "ActionEvidenceExtractor",
    "AdjudicationPolicy",
    "AdjudicationResult",
    "BoundaryRefinementPolicy",
    "BoundaryRefiner",
    "CandidateEventManager",
    "CrossRecordingEventIdentityError",
    "EventIdAllocator",
    "EventIdentityAllocationError",
    "EventIdentityAssignment",
    "EventIdentityAssignmentDisposition",
    "EventIdentityAssignmentRelation",
    "EventIdentityBatchResult",
    "EventIdentityCandidate",
    "EventIdentityCandidateRelation",
    "EventIdentityConflictError",
    "EventIdentityInputError",
    "EventIdentityOutboxRecord",
    "EventIdentityPolicyRef",
    "EventIdentityRegistryError",
    "EventIdentityRegistryMutation",
    "EventIdentityRegistryRepository",
    "EventIdentityRegistryService",
    "EventIdentityRelation",
    "EventIdentityResolution",
    "EventIdentityResolver",
    "EventProposer",
    "EventProposerConfig",
    "EventRegistrySnapshot",
    "ExactFingerprintEventIdentityResolver",
    "FusionAdjudicator",
    "FusionDecision",
    "FusionEngine",
    "FusionPolicy",
    "InMemoryEventIdentityRegistryRepository",
    "MCAPRecording",
    "PlatformEnrichedEventHypothesis",
    "PlatformEnrichedOutputReference",
    "ProductionAdmissionProof",
    "ProductionAdmittedHypothesisFact",
    "ProductionOutputAdmissionPolicyRef",
    "ProductionOutputAdmissionProof",
    "RandomEventIdAllocator",
    "RefinedEvent",
    "StableEventIdentity",
    "StaleEventRegistryFenceError",
    "TemporalSignal",
    "ValidationIssue",
    "ValidationResult",
]
