"""Queue delivery, durable-work, barrier, and publication contracts.

The durable work ledger is authoritative for scheduling state. Task-queue
adapters are optional delivery transports and cannot commit ledger outcomes.
"""

from robata.queue.backpressure import (
    AdmissionDecision,
    BackpressureConfig,
    BackpressureController,
    PressureClass,
    QueueMetrics,
    SheddingAction,
)
from robata.queue.barrier import (
    AggregateStatus,
    Barrier,
    BarrierCoordinator,
    BarrierMember,
    BarrierState,
    BarrierStorage,
    InMemoryBarrierStorage,
    ReductionPolicy,
)
from robata.queue.dispatcher import (
    CapacityReservation,
    DispatcherConfig,
    DispatchResult,
    StageDispatcher,
)
from robata.queue.models import (
    DependencyCriticality,
    WorkAttempt,
    WorkAttemptOutcome,
    WorkBarrier,
    WorkBarrierMember,
    WorkDependency,
    WorkItem,
    WorkItemPlan,
    WorkItemState,
    WorkItemSubjectType,
    WorkLease,
    WorkLeaseClaim,
)
from robata.queue.outbox import (
    IdempotentOutboxSink,
    OutboxDeliveryClaim,
    OutboxDeliveryError,
    OutboxDeliverySnapshot,
    OutboxDeliveryStatus,
    OutboxDeliveryStore,
    OutboxFenceError,
    OutboxMessage,
    OutboxRelay,
    OutboxRetryPolicy,
)
from robata.queue.redis_adapter import RedisTaskQueue
from robata.queue.stage import Stage, StageStatus
from robata.queue.wire import (
    PERSISTED_BARRIER_PROJECTION_VERSION,
    PERSISTED_BARRIER_SCHEMA_ID,
    PERSISTED_BARRIER_SCHEMA_VERSION,
    PERSISTED_BARRIER_WIRE_VERSION,
    WORK_MESSAGE_PROJECTION_VERSION,
    WORK_MESSAGE_SCHEMA_ID,
    WORK_MESSAGE_SCHEMA_VERSION,
    WORK_MESSAGE_WIRE_VERSION,
    PersistedBarrier,
    PersistedBarrierMember,
    PersistedBarrierStatus,
    WorkMessage,
    WorkMessageDependency,
    validate_registered_persisted_barrier,
    validate_registered_work_message,
)

__all__ = [
    "PERSISTED_BARRIER_PROJECTION_VERSION",
    "PERSISTED_BARRIER_SCHEMA_ID",
    "PERSISTED_BARRIER_SCHEMA_VERSION",
    "PERSISTED_BARRIER_WIRE_VERSION",
    "WORK_MESSAGE_PROJECTION_VERSION",
    "WORK_MESSAGE_SCHEMA_ID",
    "WORK_MESSAGE_SCHEMA_VERSION",
    "WORK_MESSAGE_WIRE_VERSION",
    "AdmissionDecision",
    "AggregateStatus",
    "BackpressureConfig",
    "BackpressureController",
    "Barrier",
    "BarrierCoordinator",
    "BarrierMember",
    "BarrierState",
    "BarrierStorage",
    "CapacityReservation",
    "DependencyCriticality",
    "DispatchResult",
    "DispatcherConfig",
    "IdempotentOutboxSink",
    "InMemoryBarrierStorage",
    "OutboxDeliveryClaim",
    "OutboxDeliveryError",
    "OutboxDeliverySnapshot",
    "OutboxDeliveryStatus",
    "OutboxDeliveryStore",
    "OutboxFenceError",
    "OutboxMessage",
    "OutboxRelay",
    "OutboxRetryPolicy",
    "PersistedBarrier",
    "PersistedBarrierMember",
    "PersistedBarrierStatus",
    "PressureClass",
    "QueueMetrics",
    "RedisTaskQueue",
    "ReductionPolicy",
    "SheddingAction",
    "Stage",
    "StageDispatcher",
    "StageStatus",
    "WorkAttempt",
    "WorkAttemptOutcome",
    "WorkBarrier",
    "WorkBarrierMember",
    "WorkDependency",
    "WorkItem",
    "WorkItemPlan",
    "WorkItemState",
    "WorkItemSubjectType",
    "WorkLease",
    "WorkLeaseClaim",
    "WorkMessage",
    "WorkMessageDependency",
    "validate_registered_persisted_barrier",
    "validate_registered_work_message",
]
