"""Shared wire and domain contract primitives."""

from robata.contracts.cameras import (
    CAMERA_ID_VALUES,
    CAMERA_IDS,
    CameraId,
    SixCameraMap,
)
from robata.contracts.common import (
    INT64_MAX,
    INT64_MIN,
    ContractModel,
    NanosecondInterval,
    Nanoseconds,
    SchemaVersion,
    Sha256Digest,
    StrictModel,
    ValidationIssue,
    ValidationOutcome,
    ValidationSeverity,
)
from robata.contracts.hashing import (
    CanonicalizationError,
    canonical_json_bytes,
    exact_bytes_sha256,
    recording_identity,
    semantic_sha256,
)
from robata.contracts.logical_nodes import (
    KeyNamespace,
    LogicalNode,
    NodeLogicalKey,
    NodeType,
    OpaqueUuid,
    ProcessingRunNodeMembership,
    Rfc3339Timestamp,
    RunNodeDisposition,
    RunNodeRole,
    logical_node_from_semantic_digest,
)

__all__ = [
    "CAMERA_IDS",
    "CAMERA_ID_VALUES",
    "INT64_MAX",
    "INT64_MIN",
    "CameraId",
    "CanonicalizationError",
    "ContractModel",
    "KeyNamespace",
    "LogicalNode",
    "NanosecondInterval",
    "Nanoseconds",
    "NodeLogicalKey",
    "NodeType",
    "OpaqueUuid",
    "ProcessingRunNodeMembership",
    "Rfc3339Timestamp",
    "RunNodeDisposition",
    "RunNodeRole",
    "SchemaVersion",
    "Sha256Digest",
    "SixCameraMap",
    "StrictModel",
    "ValidationIssue",
    "ValidationOutcome",
    "ValidationSeverity",
    "canonical_json_bytes",
    "exact_bytes_sha256",
    "logical_node_from_semantic_digest",
    "recording_identity",
    "semantic_sha256",
]
