"""Runtime benchmark helpers for local execution."""

from robata.runtime.benchmark import (
    BenchmarkSummary,
    ResourceSample,
    ThroughputSample,
    measure_callable,
    measure_callable_with_resources,
    run_repeated,
    summarize_samples,
)
from robata.runtime.capacity import (
    BottleneckKind,
    CapacityRegressionPolicy,
    CapacityRegressionResult,
    LatencySummary,
    LocalSloEvaluation,
    LocalSloPolicy,
    SyntheticCapacityReport,
    SyntheticLoadProfile,
    SyntheticObservation,
    SyntheticOutcome,
    SyntheticWorkUnit,
    compare_capacity_reports,
    evaluate_local_slo,
    generate_synthetic_load,
    simulate_capacity,
)

__all__ = [
    "BenchmarkSummary",
    "BottleneckKind",
    "CapacityRegressionPolicy",
    "CapacityRegressionResult",
    "LatencySummary",
    "LocalSloEvaluation",
    "LocalSloPolicy",
    "ResourceSample",
    "SyntheticCapacityReport",
    "SyntheticLoadProfile",
    "SyntheticObservation",
    "SyntheticOutcome",
    "SyntheticWorkUnit",
    "ThroughputSample",
    "compare_capacity_reports",
    "evaluate_local_slo",
    "generate_synthetic_load",
    "measure_callable",
    "measure_callable_with_resources",
    "run_repeated",
    "simulate_capacity",
    "summarize_samples",
]
