"""Runtime evidence and benchmark helpers for local execution."""

from robata.capacity import (
    CapacityPlanner,
    CapacityReport,
    CapacityScenario,
    MeasurementStatus,
    SLADeadline,
    SLAPlanner,
    SLAStage,
    StageCapacity,
    ThroughputLedger,
    ThroughputTarget,
    calibrate_capacity_scenarios,
)
from robata.runtime.benchmark import (
    BenchmarkSummary,
    ResourceSample,
    ThroughputSample,
    measure_callable,
    measure_callable_with_resources,
    run_repeated,
    summarize_samples,
)
from robata.runtime.execution import (
    EXECUTION_AUDIT_FILENAME,
    EXECUTION_MANIFEST_FILENAME,
    EXECUTION_MODE,
    EXECUTION_SCHEMA_VERSION,
    ExecutionEvidenceError,
    PublishedExecutionEvidence,
    build_execution_manifest,
    execution_manifest_semantic_sha256,
    verify_execution_evidence,
    write_execution_evidence,
)
from robata.runtime.observability import (
    MetricPoint,
    MetricsRegistry,
    StructuredLogger,
    build_log_event,
    correlation_scope,
    current_correlation_id,
    new_correlation_id,
)
from robata.runtime.preflight import EXPECTED_EXECUTION_SPEC_SHA256, REQUIRED_IMPORTS, run_preflight
from robata.runtime.process_pool_poc import (
    PngReuseReport,
    ReusablePngEncoder,
    SpawnProbeReport,
    compare_png_reuse,
    run_spawn_probe,
)
from robata.runtime.synthetic_benchmark import (
    BenchmarkCertificationError,
    SyntheticBenchmarkReport,
    SyntheticFixture,
    build_synthetic_fixtures,
    certify_summary,
    run_synthetic_benchmark,
)
from robata.runtime.verification import LocalMainlineVerificationError, verify_local_mainline_output

__all__ = [
    "EXECUTION_AUDIT_FILENAME",
    "EXECUTION_MANIFEST_FILENAME",
    "EXECUTION_MODE",
    "EXECUTION_SCHEMA_VERSION",
    "EXPECTED_EXECUTION_SPEC_SHA256",
    "REQUIRED_IMPORTS",
    "BenchmarkCertificationError",
    "BenchmarkSummary",
    "CapacityPlanner",
    "CapacityReport",
    "CapacityScenario",
    "ExecutionEvidenceError",
    "LocalMainlineVerificationError",
    "MeasurementStatus",
    "MetricPoint",
    "MetricsRegistry",
    "PngReuseReport",
    "PublishedExecutionEvidence",
    "ResourceSample",
    "ReusablePngEncoder",
    "SLADeadline",
    "SLAPlanner",
    "SLAStage",
    "SpawnProbeReport",
    "StageCapacity",
    "StructuredLogger",
    "SyntheticBenchmarkReport",
    "SyntheticFixture",
    "ThroughputLedger",
    "ThroughputSample",
    "ThroughputTarget",
    "build_execution_manifest",
    "build_log_event",
    "build_synthetic_fixtures",
    "calibrate_capacity_scenarios",
    "certify_summary",
    "compare_png_reuse",
    "correlation_scope",
    "current_correlation_id",
    "execution_manifest_semantic_sha256",
    "measure_callable",
    "measure_callable_with_resources",
    "new_correlation_id",
    "run_preflight",
    "run_repeated",
    "run_spawn_probe",
    "run_synthetic_benchmark",
    "summarize_samples",
    "verify_execution_evidence",
    "verify_local_mainline_output",
    "write_execution_evidence",
]
